version: '3.8'
services:
  book_postgres:
    image: postgres:13
    container_name: book_postgres
    environment:
      POSTGRES_DB: bookservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432" # Use port 5433 on the host
    volumes:
      - book_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bookservice:
    image: ribaso/bookservice:latest
    container_name: bookservice
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book_postgres:5432/bookservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - book_postgres
      - rabbitmq

  basket_postgres:
    image: postgres:13
    container_name: basket_postgres
    environment:
      POSTGRES_DB: basketservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5434:5432" # Use port 5434 on the host
    volumes:
      - basket_postgres_data:/var/lib/postgresql/data

  basketservice:
    image: ribaso/basketservice:latest
    container_name: basketservice
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://basket_postgres:5432/basketservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - basket_postgres
      - rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - book_postgres
      - basket_postgres

  checkout_postgres:
    image: postgres:13
    container_name: checkout_postgres
    environment:
      POSTGRES_DB: checkoutservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5435:5432" # Unique port for the checkoutservice database
    volumes:
      - checkout_postgres_data:/var/lib/postgresql/data

  checkoutservice:
    image: ribaso/checkoutservice:latest
    container_name: checkoutservice
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://checkout_postgres:5432/checkoutservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - checkout_postgres
      - rabbitmq

  user_postgres:
    image: postgres:13
    container_name: user_postgres
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5436:5432" # Unique port for the userservice database
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  userservice:
    image: ribaso/userservice:latest
    container_name: userservice
    ports:
      - "8083:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user_postgres:5432/userservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - user_postgres
      - rabbitmq


  bookmonkey-api:
    image: ribaso/bookmonkey:latest  
    ports:
      - "4730:4730"
    volumes:
      - bookmonkey_data:/var/lib/bookmonkey
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "false"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--http-port", "8080"]
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/var/lib/keycloak/data

  frontend:
    image: ribaso/frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80"
   
      


volumes:
  book_postgres_data:
  basket_postgres_data:
  checkout_postgres_data:
  user_postgres_data:
  bookmonkey_data:
  keycloak_data: