version: '3.8'
services:
  book_postgres:
    image: postgres:13
    container_name: book_postgres
    environment:
      POSTGRES_DB: bookservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432" # Use port 5433 on the host
    volumes:
      - book_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  bookservice:
    image: ribaso/bookservice:latest
    container_name: bookservice
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://book_postgres:5432/bookservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - book_postgres
      - rabbitmq

  basket_postgres:
    image: postgres:13
    container_name: basket_postgres
    environment:
      POSTGRES_DB: basketservice
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5434:5432" # Use port 5434 on the host
    volumes:
      - basket_postgres_data:/var/lib/postgresql/data

  basketservice:
    image: ribaso/basketservice:latest
    container_name: basketservice
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://basket_postgres:5432/basketservice
      SPRING_DATASOURCE_USERNAME: yourusername
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - basket_postgres
      - rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - book_postgres
      - basket_postgres

volumes:
  book_postgres_data:
  basket_postgres_data:
